global:
  resolve_timeout: "5m"

route:
  receiver: pushover
  group_by: [alertname]
  group_wait: "30s"
  group_interval: "5m"
  repeat_interval: "4h"

receivers:
  - name: pushover
    pushover_configs:
      - title: '{{ template "pushover.default.title" . }}'
        message: '{{ template "pushover.default.message" . }}'
        url: '{{ template "pushover.default.url" . }}'
        priority: '{{ with index .Alerts 0 }}{{ if eq .Labels.severity "critical" }}2{{ else if eq .Labels.severity "warning" }}0{{ else if eq .Labels.severity "info" }}-1{{ else }}0{{ end }}{{ end }}'
        send_resolved: true
        retry: "1m"
        expire: "1h"
        user_key_file: /secrets/pushover.key
        token_file: /secrets/pushover.token
